import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/ui/navbar"
import { cookies } from "next/headers"
import type { ReactNode } from "react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const initialTheme = cookies().get("theme")?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en" className={initialTheme === "dark" ? "dark" : ""}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar initialTheme={initialTheme} />
        <main>{children}</main>
      </body>
    </html>
  );
}
