import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/ui/navbar"
import { cookies } from "next/headers"
import type { ReactNode } from "react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Antholem",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo-light.ico",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/logo-dark.ico",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const cookieStore = await cookies()
  const initialTheme = cookieStore.get("theme")?.value === "dark" ? "dark" : "light"

  return (
    <html lang="en" className={initialTheme === "dark" ? "dark" : ""}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar initialTheme={initialTheme} />
        <main>{children}</main>
      </body>
    </html>
  );
}
