name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_web_react_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portfolio/client 
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB_PORTFOLIO_PROJECTS }}
          channelId: live
          projectId: web-portfolio-projects
          entryPoint: portfolio/client
